name = "nnps"
version = "1.3.0"
license = "MIT"
author = "ZUO Zhihua"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2021~2023 ZUO Zhihua"

[build]
auto-examples = true

[dependencies]
openmp = "*"

[dev-dependencies]
test-drive = { git = "https://gitee.com/fortran-base/test-drive", tag = "v0.4.0" }
display = { git = "https://gitee.com/zoziha/display" }
random = { git = "https://gitee.com/zoziha/random" }
timer = { git = "https://gitee.com/zoziha/timer" }

[install]
library = true

[preprocess.cpp]
# 取消注释以启用串行版本
# macros = ["SERIAL"]
