name = "nnps"
version = "1.0.0"
license = "MIT"
author = "ZUO Zhihua"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2021~2023 ZUO Zhihua"

[build]
auto-examples = true

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive", tag = "v0.4.0" }
display = { git = "https://gitee.com/zoziha/display" }
openmp = "*"

[install]
library = true
