name = "quad-tree"
version = "0.1.0"
license = "MIT"
author = "左志华"
maintainer = "@quad-tree contributors"
copyright = "2021~2022 quad-tree contributors"

[dependencies]
forlab = { git="https://github.com/fortran-fans/forlab", branch="forlab-fpm" }

[build]
auto-examples = true
